#port
port: 2048
# access the hexo editor directly
local: true
# the username to login hexo editor
username: hexo
# the password for logining hexo editor
password: imyouradmin
# the blog directory
base_dir: /home/tajpure/workspace/blog1
