# access the hexo editor directly
local: false

# the username to login hexo editor
username: hexo

# the password for logining hexo editor
password: imyouradmin

# the blog directory
base_dir: ./docs

# port
port: 2048
